config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  devise_for :users, path: "auth", path_names: { 
  	sign_in: "login", 
  	sign_out: "logout", 
  	password: "secret", 
  	confirmation: "verification", 
  	unlock: "unblock", 
  	registration: "register", 
  	sign_up: "cmon_let_me_in" 
  }
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => "/cable"
   
  resources :chat_rooms, only: [:show, :index, :new, :create]
  resources :messages, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages

  validates :topic, presence: true, length: {maximum: 50}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :chat_room_id, :user_id, presence: true
  validates :content, presence: true, length: {maximum: 250}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    @chatroom = ChatRoom.find params[:id]
    @message = Message.new
  end

  def index
  	@chatrooms = ChatRoom.all
  end

  def new
  	@chatroom = ChatRoom.new
  end

  def create
  end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
  	message = current_user.messages.build message_params  	
    if message.save
      ActionCable.server.broadcast "messages_#{message.chat_room_id}_channel",
        message: message.content,
        user: current_user.email
      head :ok
    else 
      redirect_to chatrooms_path
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :chat_room_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chat_rooms/_chat_room_form.html.erb
<%= form_for chat_room, authenticity_token: true do |f| %>
  <%= f.label :topic %>:
  <%= f.text_field :topic, class: "form-control" %>
  <%= f.label :slug %>:
  <%= f.text_field :slug, class: "form-control" %>
  <%= f.submit "Create", class: "btn btn-primary", data: {send: "message"}%>
<%end%>

app/views/chat_rooms/index.html.erb
<h1>ChatRooms#index</h1>
<p>Find me in app/views/chat_rooms/index.html.erb</p>

<%= link_to "New Topic", new_chat_room_path %>

<table>
  <tr>
  	<th>ID</th>
  	<th>Topic</th>
  	<th>Action</th>
  </tr>
  <% @chatrooms.each do |chatroom| %>
  <tr>
    <td><%= chatroom.id %></td>
    <td><%= chatroom.topic %></td>
    <td><%= link_to "Join", chat_room_path(chatroom) %></td>
  </tr>
  <% end %>
</table>

app/views/chat_rooms/new.html.erb
<%= render "chat_room_form", chat_room: @chatroom %>

app/views/chat_rooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <% if @chatroom.messages.any? %>
    <div class="panel-body" id="messages" data-chat-room-id="<%= @chatroom.id %>">
      <%= render partial: "messages/message", collection: @chatroom.messages %>
    </div>
  <%else%>
    <div class="panel-body hidden" id="messages" data-chat-room-id="<%= @chatroom.id %>">
    </div>
  <%end%>
</div>

  <%= render partial: "messages/message_form", locals: {message: @message, chatroom: @chatroom}%>
</div>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p> 
  <b><%= message.user.email %> : 
  </b><%= message.content %>
</p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <%= f.text_area :content, class: "form-control", id: "message_content", data: {textarea: "message", current_user_id: current_user.id} %>
  <%= f.hidden_field :chat_room_id, value: chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", data: {send: "message"}%>
<%end%>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>